---
baseurl: "https://rtmp.veriskope.com"
title: "Real-Time Messaging Protocol (RTMP)"
languageCode: "en-us"
canonifyURLs: "true"
googleAnalytics: "UA-132929302-1"
params:

markup:
  goldmark:
    renderer:
      unsafe: true
